### ISSUE TITLE
Maven issue

### ISSUE THREAD

**Issue by C0mmander198** [Azure/azure-documentdb-hadoop#6]
When trying to package this using Maven I get the following errors in the DocumentDBSerDe.java:

[ERROR] /tmp/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/DocumentDBSerDe.java:[16,32] package org.openx.data.jsonserde does not exist
[ERROR] /tmp/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/DocumentDBSerDe.java:[17,37] package org.openx.data.jsonserde.json does not exist

Is there some reference to the jsonserde project not set correctly or am I doing something wrong?

**Comment by AndrewHoh** [comment]
The issue is that the DocumentDBSerDe.java has a dependency on the org.openx.data.jsonserde. This jsonserde is not published on maven, so you have to download the dependency from here https://github.com/rcongiu/Hive-JSON-Serde/releases. Afterwards, you can add the downloaded dependency to your maven local repository. This should solve your problem.

**Comment by C0mmander198** [comment]
This is correct. I installed the Hive-JSON-Serde project to my local repository. But afterwards I had to add this to the pom.xml of the azure-documentdb-hadoop project to make it work:
    <'dependency>
        <'groupId>org.openx.data<'/groupId>
        <'artifactId>json-serde<'/artifactId>
        <'version>1.3.6-SNAPSHOT<'/version>
    <'/dependency>

**Comment by AndrewHoh** [comment]
Glad to hear you got it working! If you have any other questions, feel free to post a comment.
